######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 20 20:12:14 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h TicTacToeLoeser.h TicTacToeSpiel.h
FORMS += MainWindow.ui
SOURCES += main.cpp MainWindow.cpp TicTacToeLoeser.cpp TicTacToeSpiel.cpp
RESOURCES += resourcen.qrc
TRANSLATIONS += Uebersetzung_de.ts
